- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable'

- name: Install nginx
  action: apt pkg=nginx-extras state=installed update_cache=true

- name: add nginx config
  template: src=nginx dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: add .htpasswd
  template: src=htpasswd dest=/var/www/.htpasswd force=no
  notify: restart nginx

- name: add sites config
  template: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item | basename }}
  with_fileglob:
    - ../templates/*.conf
  notify: restart nginx

#- name: Disable default site
#  file: 
#    path: /etc/nginx/sites-enabled/default
#    state: absent