- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable'

- name: Install nginx
  action: apt pkg=nginx-extras state=installed update_cache=true

- name: add dev config
  template: src=dev.conf dest=/etc/nginx/sites-enabled/dev.conf
  notify: restart nginx

#- name: Disable default site
#  file: 
#    path: /etc/nginx/sites-enabled/default
#    state: absent
