- hosts: vps
  sudo: yes
  vars:
    - user_name: "test"
    - user_password: "123"
    - mysql_root_password: 123
  roles:
  - { role: base }
  - { role: nginx }
  - { role: nodejs }
  - { role: php7 }
  - { role: mysql }
  - { role: user }
