- hosts: vps
  sudo: yes
  vars:
    - user_name: "test"
    - user_password: "123"
    - mysql_root_password: 123
  roles:
  - { role: user }
  - { role: base }
  - { role: nginx }
  - { role: nodejs }
  - { role: php7 }
  - { role: sendmail }
  - { role: phpmyadmin }
  - { role: docker }
  - { role: linux-swap }
