set autoindent
set cindent
set nocompatible
"set term=ansi
"set term=builtin_ansi
"set term=cons25
set timeout ttimeoutlen=100 timeoutlen=5000
set encoding=utf-8

set backspace=2 " make backspace work like most other apps
set number
set ruler

execute pathogen#infect()

" = Theme
set background=dark
set t_Co=256
colorscheme xoria256

let g:airline_powerline_fonts = 1

" = AutoSave
let g:auto_save = 1  " enable AutoSave on Vim startup
let g:auto_save_in_insert_mode = 0  " do not save while in insert mode

" = vim-easymotion
map <Leader> <Plug>(easymotion-prefix)

" = NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

let NERDTreeShowHidden=1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
hi Directory guifg=#FF0000 ctermfg=166



set list listchars=tab:→\ ,trail:·
highlight SpecialKey ctermfg=8

" = Mouse

" Send more characters for redraws 
set ttyfast  

" Enable mouse use in all modes 
set mouse=a  

" Set this to the name of your terminal that supports mouse codes. 
" Must be one of: xterm, xterm2, netterm, dec, jsbterm, pterm 
set ttymouse=xterm2


" = PHP

let g:phpcomplete_mappings = {
   \ 'jump_to_def': '<C-]>',
   \ 'jump_to_def_split': '<C-W><C-]>',
   \ 'jump_to_def_vsplit': '<C-W><C-\>',
   \}


"let g:phpcomplete_active_function_extensions
"let g:phpcomplete_active_class_extensions
"let g:phpcomplete_active_interface_extensions
"let g:phpcomplete_active_constant_extensions


