set autoindent
set cindent
set nocompatible
"set term=ansi
"set term=builtin_ansi
"set term=cons25
set timeout ttimeoutlen=100 timeoutlen=5000
set encoding=utf-8

set backspace=2 " make backspace work like most other apps
set number
set ruler

execute pathogen#infect()

" = Theme
set background=dark
set t_Co=256
"colorscheme xoria256
colorscheme darcula

let g:airline_powerline_fonts = 1

" = AutoSave
let g:auto_save = 1  " enable AutoSave on Vim startup
let g:auto_save_in_insert_mode = 0  " do not save while in insert mode

" = vim-easymotion
map <Leader> <Plug>(easymotion-prefix)

" = NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

let NERDTreeShowHidden=1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
hi Directory guifg=#FF0000 ctermfg=166

" NERS tree git
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "*",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }

" = Buffer tabs
set hidden
nnoremap <F2> :BD<CR>
nnoremap <F3> :bprev<CR>
nnoremap <F4> :bnext<CR>
let g:buftabline_numbers=1 "show buffer number
let g:buftabline_separators=1 "show separators between tabs

set list listchars=tab:→\ ,trail:·
highlight SpecialKey ctermfg=8

" = Mouse

" Send more characters for redraws 
set ttyfast  

" Enable mouse use in all modes 
set mouse=a  
"set mouse=nicr

" Set this to the name of your terminal that supports mouse codes. 
" Must be one of: xterm, xterm2, netterm, dec, jsbterm, pterm 
set ttymouse=xterm2

function! SwitchMouseMode()
	if &mouse == 'a'
		:set mouse=nicr
	else
		:set mouse=a
	endif
endfunction
noremap <F5> :call SwitchMouseMode()<CR>

" = PHP

let g:phpcomplete_mappings = {
   \ 'jump_to_def': '<C-]>',
   \ 'jump_to_def_split': '<C-W><C-]>',
   \ 'jump_to_def_vsplit': '<C-W><C-\>',
   \}


"let g:phpcomplete_active_function_extensions
"let g:phpcomplete_active_class_extensions
"let g:phpcomplete_active_interface_extensions
"let g:phpcomplete_active_constant_extensions


" = HotKeys


