- name: install packages
  apt: 
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates

- name: add key
  command: bash -lc "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"

- name: add source
  template: src=docker.list dest=/etc/apt/sources.list.d/docker.list force=no
  register: docker_repo

- name: update cache
  apt: update_cache=yes
  when: docker_repo.changed 

- name: install docker-engine
  apt: name=docker-engine update_cache=yes
  notify: restart docker

#- name: Create the docker group
#  command: bash -lc "groupadd docker"

#- name: Add your user to docker group
#  command: bash -lc "usermod -aG docker ubuntu"

- name: Download docker-compose
  command: bash -lc "curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"

- name: Permissions docker-compose
  command: bash -lc "chmod +x /usr/local/bin/docker-compose"
