- name: create folder .vim
  file: path=/home/{{ user_name }}/.vim state=directory mode=0755

- name: create folder autoload
  file: path=/home/{{ user_name }}/.vim/autoload state=directory mode=0755

- name: delete folder bundle
  shell: rm -rf /home/{{ user_name }}/.vim/bundle

- name: create folder bundle
  file: path=/home/{{ user_name }}/.vim/bundle state=directory mode=0755

- name: install pathogen
  get_url: url=https://tpo.pe/pathogen.vim dest=/home/{{ user_name }}/.vim/autoload/pathogen.vim mode=0755  owner={{ user_name }}

- name: add .vimrc
  template: src=vimrc dest=/home/{{ user_name }}/.vim/vimrc owner={{ user_name }}

- name: symlink .vimrc
  file:
    src: /home/{{ user_name }}/.vim/vimrc
    dest: /home/{{ user_name }}/.vimrc
    state: link

# Themes
- name: install vim themes
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/vim-scripts/xoria256.vim.git
          folder: xoria256.vim
        -
          url: https://github.com/blueshirts/darcula.git
          folder: darcula


# Vim Buffer
- name: install vim buffer
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/qpkorr/vim-bufkill.git
          folder: vim-bufkill
        -
          url: https://github.com/ap/vim-buftabline.git
          folder: vim-buftabline

# Plugins
- name: install vim plugins
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/vim-airline/vim-airline.git
          folder: vim-airline
        -
          url: https://github.com/SirVer/ultisnips.git
          folder: ultisnips
        -
          url: https://github.com/tomtom/tcomment_vim.git
          folder: tcomment_vim
        -
          url: https://github.com/gioele/vim-autoswap.git
          folder: vim-autoswap
        -
          url: https://github.com/scrooloose/syntastic.git
          folder: syntastic
        -
          url: https://github.com/easymotion/vim-easymotion.git
          folder: vim-easymotion
        -
          url: https://github.com/takac/vim-hardtime.git
          folder: vim-hardtime

# Git
- name: install vim git plugins
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/tpope/vim-fugitive.git
          folder: vim-fugitive

# Similar IDE
- name: install vim Similar IDE plugins
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/scrooloose/nerdtree.git
          folder: nerdtree
        -
          url: https://github.com/Xuyuanp/nerdtree-git-plugin.git
          folder: nerdtree-git-plugin
        -
          url: https://github.com/vim-scripts/vim-auto-save.git
          folder: vim-auto-save
        -
          url: https://github.com/editorconfig/editorconfig-vim.git
          folder: editorconfig-vim
        -
          url: https://github.com/kien/ctrlp.vim.git
          folder: ctrlp.vim
        -
          url: https://github.com/tpope/vim-surround.git
          folder: vim-surround

# PHP
- name: install vim PHP plugins
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/StanAngeloff/php.vim.git
          folder: php.vim
        -
          url: https://github.com/stephpy/vim-php-cs-fixer.git
          folder: vim-php-cs-fixer
        -
          url: https://github.com/shawncplus/phpcomplete.vim.git
          folder: phpcomplete.vim

# Frontend
- name: install vim Frontend plugins
  git: repo={{ item.url }} dest=/home/{{ user_name }}/.vim/bundle/{{ item.folder }} depth=1 force=no
  with_items:
        -
          url: https://github.com/kchmck/vim-coffee-script.git
          folder: vim-coffee-script
        -
          url: https://github.com/posva/vim-vue.git
          folder: vim-vue
