- name: create folder .vim
  file: path=/home/{{ user_name }}/.vim state=directory mode=0755

- name: create folder autoload
  file: path=/home/{{ user_name }}/.vim/autoload state=directory mode=0755

- name: create folder bundle
  file: path=/home/{{ user_name }}/.vim/bundle state=directory mode=0755

- name: install pathogen
  get_url: url=https://tpo.pe/pathogen.vim dest=/home/{{ user_name }}/.vim/autoload/pathogen.vim mode=0755  owner={{ user_name }}

- name: add .vimrc
  template: src=vimrc dest=/home/{{ user_name }}/.vim/vimrc owner={{ user_name }}

- name: symlink .vimrc
  file:
    src: /home/{{ user_name }}/.vim/vimrc
    dest: /home/{{ user_name }}/.vimrc
    state: link

# Theme
- name: install plugin xoria256.vim
  git: repo=https://github.com/vim-scripts/xoria256.vim.git dest=/home/{{ user_name }}/.vim/bundle/xoria256.vim depth=1 force=no

# Plugins
- name: install plugin vim-airline
  git: repo=https://github.com/vim-airline/vim-airline.git dest=/home/{{ user_name }}/.vim/bundle/vim-airline depth=1 force=no

- name: install plugin ultisnips
  git: repo=https://github.com/SirVer/ultisnips.git dest=/home/{{ user_name }}/.vim/bundle/ultisnips depth=1 force=no

- name: install plugin tcomment_vim
  git: repo=https://github.com/tomtom/tcomment_vim.git dest=/home/{{ user_name }}/.vim/bundle/tcomment_vim depth=1 force=no

- name: install plugin tabular
  git: repo=https://github.com/godlygeek/tabular.git dest=/home/{{ user_name }}/.vim/bundle/tabular depth=1 force=no

- name: install plugin syntastic
  git: repo=https://github.com/scrooloose/syntastic.git dest=/home/{{ user_name }}/.vim/bundle/syntastic depth=1 force=no

- name: install plugin nerdcommenter
  git: repo=https://github.com/scrooloose/nerdcommenter.git dest=/home/{{ user_name }}/.vim/bundle/nerdcommenter depth=1 force=no

- name: install plugin vim-easymotion
  git: repo=https://github.com/easymotion/vim-easymotion.git dest=/home/{{ user_name }}/.vim/bundle/vim-easymotion depth=1 force=no


# similar IDE
- name: install plugin nerdtree
  git: repo=https://github.com/scrooloose/nerdtree.git dest=/home/{{ user_name }}/.vim/bundle/nerdtree depth=1 force=no

- name: install plugin buftabline
  git: repo=https://github.com/ap/vim-buftabline.git dest=/home/{{ user_name }}/.vim/bundle/vim-buftabline depth=1 force=no

- name: install plugin vim-auto-save
  git: repo=https://github.com/vim-scripts/vim-auto-save.git dest=/home/{{ user_name }}/.vim/bundle/vim-auto-save depth=1 force=no

- name: install plugin editorconfig-vim
  git: repo=https://github.com/editorconfig/editorconfig-vim.git dest=/home/{{ user_name }}/.vim/bundle/editorconfig-vim depth=1 force=no

- name: install plugin auto-pairs
  git: repo=https://github.com/yukunlin/auto-pairs.git dest=/home/{{ user_name }}/.vim/bundle/auto-pairs depth=1 force=no

# php

- name: install plugin php.vim
  git: repo=https://github.com/StanAngeloff/php.vim.git dest=/home/{{ user_name }}/.vim/bundle/php.vim depth=1 force=no

- name: install plugin vim-php-cs-fixer
  git: repo=https://github.com/stephpy/vim-php-cs-fixer.git dest=/home/{{ user_name }}/.vim/bundle/vim-php-cs-fixer depth=1 force=no

- name: install plugin phpcomplete.vim
  git: repo=https://github.com/shawncplus/phpcomplete.vim.git dest=/home/{{ user_name }}/.vim/bundle/phpcomplete.vim depth=1 force=no

# frontend

- name: install plugin vim-coffee-script
  git: repo=https://github.com/kchmck/vim-coffee-script.git dest=/home/{{ user_name }}/.vim/bundle/vim-coffee-script depth=1 force=no
